### PR TITLE
fix(cli): validate channel credential types

### LINKED ISSUE #5717: bug(cli): channel credentials require string values
## What happened?

`parseChannelConfig()` resolves env vars for known credential fields (`token`, `clientId`, `clientSecret`) by casting truthy config values to string:

```ts
resolveEnvVars(rawConfig['token'] as string)
```

If a user configures one of those fields with a non-string value, such as:

```json
{ "type": "telegram", "token": 123 }
```

the parser can throw an internal TypeError from `value.startsWith` instead of a useful configuration error naming the invalid field.

## Expected behavior

Known channel credential fields should be validated as strings before env-var resolution. Invalid types should produce a clear config error that names the channel and field, e.g. `Channel "bot" field "token" must be a string.`

## Notes

Relevant code:

- `packages/cli/src/commands/channel/config-utils.ts`
- `packages/cli/src/commands/channel/config-utils.test.ts`

### PR DESCRIPTION
**Pull request by tt-a1i**
## What this PR does

This PR validates channel credential fields before resolving environment variables. `token`, `clientId`, and `clientSecret` now must be strings when present.

It also separates missing required credential fields from wrong-typed fields, so values such as `false` or `123` produce a field-specific type error instead of being reported as missing or falling through to an internal `startsWith` TypeError.

## Why it's needed

Channel settings are stored as a broad object, so invalid JSON types can reach `parseChannelConfig()`. The previous parser cast truthy credential values to `string` before calling `resolveEnvVars()`. A config like `{ "type": "telegram", "token": 123 }` could therefore fail with an internal `value.startsWith is not a function` error.

Clear configuration errors make it obvious which channel field is invalid.

### How to verify

Run the focused channel config tests and confirm non-string `token`, `clientId`, and `clientSecret` values are rejected with clear field-specific messages.

### Evidence (Before & After)

Before: non-string credential values could throw internal TypeErrors from env-var resolution, and falsy non-string required values could be reported as missing.

After: non-string credential values fail with messages like `Channel "bot" field "token" must be a string.`, while missing values still use the existing required-field error.

### Tested on

|     OS     | Status |
| :--------: | :----: |
|  🍏 macOS  | ✅ tested |
| 🪟 Windows | ⚠️ not tested |
|  🐧 Linux  | ⚠️ not tested |

### Environment (optional)

Local workspace tests on macOS with the repository npm workspace setup.

Commands run:

```sh
npm test --workspace=packages/cli -- commands/channel/config-utils.test.ts --coverage.enabled=false
npx prettier --check packages/cli/src/commands/channel/config-utils.ts packages/cli/src/commands/channel/config-utils.test.ts
npx eslint packages/cli/src/commands/channel/config-utils.ts packages/cli/src/commands/channel/config-utils.test.ts
git diff --check
```

Also run:

```sh
npm run typecheck --workspace=packages/cli --if-present
```

This currently fails on unrelated existing `BaseTextInput.tsx` / `ink` type resolution errors:

```text
src/ui/components/BaseTextInput.tsx(25,52): error TS2307: Cannot find module 'ink/dom' or its corresponding type declarations.
src/ui/components/BaseTextInput.tsx(26,27): error TS2307: Cannot find module 'ink/components/CursorContext' or its corresponding type declarations.
src/ui/components/BaseTextInput.tsx(310,9): error TS18046: 'cursorCtx' is of type 'unknown'.
src/ui/components/BaseTextInput.tsx(334,7): error TS18046: 'cursorCtx' is of type 'unknown'.
src/ui/components/BaseTextInput.tsx(341,7): error TS18046: 'cursorCtx' is of type 'unknown'.
```

Sub-agent review: no blocking issues found.

## Risk & Scope

- Main risk or tradeoff: Existing invalid channel configs with non-string credential values now fail earlier with a configuration error.
- Not validated / out of scope: This PR does not validate unrelated channel settings such as `allowedUsers`, `groups`, or `senderPolicy`.
- Breaking changes / migration notes: None for valid configs.

## Linked Issues

Fixes #5717

## AI Assistance Disclosure

I used Codex to review the changes, sanity-check the implementation against existing patterns, and help spot potential edge cases.

<details>
<summary>中文说明</summary>

## What this PR does

这个 PR 会在解析环境变量之前校验 channel credential 字段。`token`、`clientId` 和 `clientSecret` 在出现时现在必须是字符串。

同时，它把缺失的必填 credential 字段和类型错误字段区分开来，因此 `false` 或 `123` 这类值会得到明确的字段类型错误，而不是被报成 missing 或继续进入内部 `startsWith` TypeError。

## Why it's needed

Channel settings 是宽泛 object，错误的 JSON 类型可能进入 `parseChannelConfig()`。之前的 parser 会在调用 `resolveEnvVars()` 前把 truthy credential 值强转成 `string`。因此 `{ "type": "telegram", "token": 123 }` 这样的配置可能以内部 `value.startsWith is not a function` 错误失败。

清晰的配置错误能让用户直接知道哪个 channel 字段无效。

### How to verify

运行 focused channel config tests，确认非字符串的 `token`、`clientId` 和 `clientSecret` 会被清晰的字段级错误拒绝。

### Evidence (Before & After)

Before: 非字符串 credential 值可能从 env-var resolution 抛内部 TypeError；falsy 的非字符串必填值也可能被误报为 missing。

After: 非字符串 credential 值会以类似 `Channel "bot" field "token" must be a string.` 的消息失败；缺失值仍使用已有 required-field 错误。

### Tested on

|     OS     | Status |
| :--------: | :----: |
|  🍏 macOS  | ✅ tested |
| 🪟 Windows | ⚠️ not tested |
|  🐧 Linux  | ⚠️ not tested |

### Environment (optional)

在 macOS 上使用仓库 npm workspace 进行本地测试。

已运行命令：

```sh
npm test --workspace=packages/cli -- commands/channel/config-utils.test.ts --coverage.enabled=false
npx prettier --check packages/cli/src/commands/channel/config-utils.ts packages/cli/src/commands/channel/config-utils.test.ts
npx eslint packages/cli/src/commands/channel/config-utils.ts packages/cli/src/commands/channel/config-utils.test.ts
git diff --check
```

也运行了：

```sh
npm run typecheck --workspace=packages/cli --if-present
```

该命令目前因既有且无关的 `BaseTextInput.tsx` / `ink` 类型解析错误失败：

```text
src/ui/components/BaseTextInput.tsx(25,52): error TS2307: Cannot find module 'ink/dom' or its corresponding type declarations.
src/ui/components/BaseTextInput.tsx(26,27): error TS2307: Cannot find module 'ink/components/CursorContext' or its corresponding type declarations.
src/ui/components/BaseTextInput.tsx(310,9): error TS18046: 'cursorCtx' is of type 'unknown'.
src/ui/components/BaseTextInput.tsx(334,7): error TS18046: 'cursorCtx' is of type 'unknown'.
src/ui/components/BaseTextInput.tsx(341,7): error TS18046: 'cursorCtx' is of type 'unknown'.
```

子代理审查：未发现阻塞问题。

## Risk & Scope

- Main risk or tradeoff: credential 字段为非字符串的无效 channel config 现在会更早以配置错误失败。
- Not validated / out of scope: 本 PR 不校验 `allowedUsers`、`groups` 或 `senderPolicy` 等其他 channel settings。
- Breaking changes / migration notes: 对有效配置无影响。

## Linked Issues

Fixes #5717

## AI Assistance Disclosure

I used Codex to review the changes, sanity-check the implementation against existing patterns, and help spot potential edge cases.

</details>

### CODE REVIEW

**Comment by wenshao** [comment]
@qwen-code /triage

**Comment by wenshao** [comment]
## ✅ Local verification report (maintainer)

Built and tested this PR locally to confirm the fix before merge.

**Environment**
- macOS (Darwin 25.5), Node `v22.22.2`
- PR head `c0294839b`, base `origin/main` `2fd2104fa` (the two channel files are identical between the PR base and current `origin/main` `896e6c59e`, so the PR head is a faithful base)
- Method: isolated `git worktree` at the PR head with a clean `npm ci` + fresh `core`/`acp-bridge` build, then verified each claim independently.

**Results**

| Check | Command | Result |
| --- | --- | --- |
| Target tests | `vitest run .../channel/config-utils.test.ts` | ✅ 17/17 pass |
| New tests | the 2 added credential-type cases | ✅ pass |
| Lint | `eslint` on both changed files | ✅ clean |
| Types | `tsc --noEmit` (`packages/cli`) | ✅ exit 0, **0 errors** |
| Format | `prettier --check` on both files | ✅ clean |

**Mutation test (the key evidence).** I reverted `config-utils.ts` back to the `main` version (the `rawConfig['token'] as string` cast) while keeping the PR's new tests. Both **fail**, reproducing the exact bug from #5717:

```
× throws a clear error when token is not a string
  → expected to throw 'Channel "bot" field "token" must be a string.'
    but got 'value.startsWith is not a function'
```

That `value.startsWith is not a function` is verbatim the internal TypeError the issue reports. The tests pin the real bug and pass once the fix is restored.

**Note on the documented typecheck failure.** The PR body says `npm run typecheck` fails on unrelated `ink/dom` / `BaseTextInput.tsx` errors. On a clean `npm ci` this does **not** reproduce — `tsc --noEmit` for `packages/cli` passes with **0 errors**. The `ink` subpath exports (`./dom`, `./components/CursorContext`) and their `.d.ts` files are present in the installed package, so `BaseTextInput.tsx` resolves fine. That failure was a stale/incomplete local install on the author's machine, not a real repo issue — the PR itself is fully type-clean.

**Correctness review**
- The new `resolveOptionalStringField()` validates `token` / `clientId` / `clientSecret` are strings *before* `resolveEnvVars()`, throwing a clear `Channel "<name>" field "<field>" must be a string.` Empty / `null` / `undefined` are treated as "not provided" (same default behavior as before).
- It cleanly separates **missing** (`undefined|null|''`) from **wrong-typed**: a required credential set to `false` / `123` now yields the accurate type error instead of a misleading "requires …" or the cryptic `startsWith` TypeError. Valid string values and `$ENV` references are unaffected.

**Minor / non-blocking observation**
- The required-field gate changed from `!rawConfig[field]` (any falsy) to explicit `undefined | null | ''`, and only the three credential fields get the string type-check. So a *non-credential* required field set to a falsy-but-present value like `0` / `false` would now pass the "required" gate without a type check. Across all bundled plugins the only such field is `plugin-example`'s `serverWsUrl` (telegram→`token`, dingtalk/feishu→`clientId`/`clientSecret`, qqbot→none are all credentials). Practically irrelevant (a template plugin + absurd input) and consistent with the PR's stated credential-only scope — could be a follow-up if you want every required field validated as a string.

**Verdict: LGTM.** Correct, mutation-verified (reproduces #5717 exactly), type-clean on a proper install, lint/format clean. Safe to merge from my side — the documented "typecheck failure" is an author-local artifact, not a blocker.

<details>
<summary>🇨🇳 中文版</summary>

## ✅ 本地验证报告（维护者）

合并前在本地构建并测试了本 PR 以确认修复。

**环境**
- macOS（Darwin 25.5），Node `v22.22.2`
- PR head `c0294839b`，base `origin/main` `2fd2104fa`（这两个 channel 文件在 PR base 与当前 `origin/main` `896e6c59e` 之间完全一致，所以 PR head 是忠实的基线）
- 方法：在 PR head 上建独立 `git worktree`，做干净的 `npm ci` 并重建 `core`/`acp-bridge`，再逐条独立验证。

**结果**

| 检查项 | 命令 | 结果 |
| --- | --- | --- |
| 目标测试 | `vitest run .../channel/config-utils.test.ts` | ✅ 17/17 通过 |
| 新增测试 | 新加的 2 个 credential 类型用例 | ✅ 通过 |
| Lint | 对两个改动文件跑 `eslint` | ✅ 干净 |
| 类型 | `tsc --noEmit`（`packages/cli`） | ✅ exit 0，**0 错误** |
| 格式 | 对两个文件跑 `prettier --check` | ✅ 干净 |

**变异测试（关键证据）。** 我把 `config-utils.ts` 还原成 `main` 上的版本（`rawConfig['token'] as string` 强转），保留 PR 的新测试。两个都**失败**，精确复现了 #5717 的 bug：

```
× throws a clear error when token is not a string
  → 期望抛 'Channel "bot" field "token" must be a string.'
    实际抛 'value.startsWith is not a function'
```

`value.startsWith is not a function` 正是 issue 描述的那个内部 TypeError。说明这些测试锁定了真实 bug，恢复修复后即通过。

**关于 PR 里记录的 typecheck 失败。** PR 正文说 `npm run typecheck` 会因无关的 `ink/dom` / `BaseTextInput.tsx` 报错而失败。在干净的 `npm ci` 下**复现不出来** —— `packages/cli` 的 `tsc --noEmit` **0 错误**通过。`ink` 的子路径导出（`./dom`、`./components/CursorContext`）及其 `.d.ts` 在装好的包里都在，`BaseTextInput.tsx` 能正常解析。那次失败是作者机器上陈旧/不完整的本地安装造成的，不是仓库的真实问题 —— 本 PR 本身类型完全干净。

**正确性审查**
- 新的 `resolveOptionalStringField()` 在 `resolveEnvVars()` **之前**校验 `token` / `clientId` / `clientSecret` 必须是字符串，否则抛清晰的 `Channel "<name>" field "<field>" must be a string.`。空串 / `null` / `undefined` 被当作「未提供」（与之前默认行为一致）。
- 它干净地把**缺失**（`undefined|null|''`）和**类型错误**区分开：必填 credential 被设成 `false` / `123` 时，现在给出准确的类型错误，而不是误导性的「requires …」或晦涩的 `startsWith` TypeError。合法字符串值和 `$ENV` 引用不受影响。

**次要 / 非阻塞观察**
- 必填字段的判断从 `!rawConfig[field]`（任意 falsy）改成了显式的 `undefined | null | ''`，而且只有这三个 credential 字段会走字符串类型校验。所以一个*非 credential* 的必填字段若被设成 `0` / `false` 这类「falsy 但存在」的值，现在会通过「必填」这道关却不被类型校验。在所有内置插件里，唯一这样的字段是 `plugin-example` 的 `serverWsUrl`（telegram→`token`、dingtalk/feishu→`clientId`/`clientSecret`、qqbot→无，都是 credential）。实际影响可忽略（模板插件 + 荒谬输入），且与本 PR「只校验 credential」的既定范围一致 —— 如果想把所有必填字段都校验成字符串，可作为后续跟进。

**结论：LGTM。** 正确、经变异测试验证（精确复现 #5717）、在正确安装下类型干净、lint/格式干净。从我这边看可以安全合并 —— 记录的「typecheck 失败」是作者本地环境产物，不是阻塞项。

</details>

**Review by wenshao — APPROVED** [review]
