### PR TITLE
fix(live-host-release): build sdk before qwen-live in publish job

### PR DESCRIPTION
**Pull request by LaZzyMan**
qwen-live depends on @qwen-code/sdk's built dist; --ignore-scripts skips the build, so tsc cannot find the module. Added an explicit sdk build step before the qwen-live build.

### CODE REVIEW

**Review by DragonnZhang — DISMISSED** [review]

**Review by qqqys — COMMENTED** [review]
Re-review at head `1711681a` — COMMENT (cannot approve).

**Critical: the new build step targets a workspace that does not exist; the publish job will fail on this step.**

`.github/workflows/live-host-release.yml`, new step inserted between "Install dependencies" and "Build qwen-live":

```yaml
- name: 'Build dependencies (sdk)'
  run: 'npm run build --workspace @qwen-code/sdk-typescript'
```

`sdk-typescript` is the **directory** name; the package name in `packages/sdk-typescript/package.json` is `@qwen-code/sdk` (qwen-live's dependency confirms it: `"@qwen-code/sdk": "file:../sdk-typescript"`). npm resolves `--workspace` by package name (or path); `@qwen-code/sdk-typescript` is neither.

Reproduction (repo root, same command as the workflow step):

```
$ npm run build --workspace '@qwen-code/sdk-typescript'
npm error No workspaces found:
npm error   --workspace=@qwen-code/sdk-typescript
(exit code 1)

$ npm ls --workspace '@qwen-code/sdk' --depth=0   # the correct specifier resolves fine
```

The step exits non-zero, so the next Host Release publish run fails here instead of at the qwen-live build — the job stays broken. No PR CI can catch this because the publish job only runs inside the release workflow.

Fix: `run: 'npm run build --workspace @qwen-code/sdk'`.

Notes:
- The setup-node SHA hunk duplicates already-merged #10827 (identical content; merges cleanly) — informational, not a blocker.
- The triage CHANGES_REQUESTED on this PR is about PR-template sections (process), not a code blocker.

CI at review time: green except `Test (ubuntu-latest, Node 22.x)` and `review-pr` pending; nothing attributable to this PR.

---

中文：新增的 `npm run build --workspace @qwen-code/sdk-typescript` 步骤指向不存在的 workspace —— `sdk-typescript` 是目录名，包名实为 `@qwen-code/sdk`（见 `packages/sdk-typescript/package.json`；qwen-live 的依赖写作 `"@qwen-code/sdk": "file:../sdk-typescript"`）。实测该命令以退出码 1 失败（`npm error No workspaces found`），发布任务下次运行会在这一步失败，原问题并未修复。修复方式：改用 `--workspace @qwen-code/sdk`。setup-node SHA 一段与已合并的 #10827 内容相同、可干净合入，仅作提示。

**Review by qqqys — APPROVED** [review]

**Review by qqqys — CHANGES_REQUESTED** [review]
## Critical — supersedes our APPROVED on this same head: the corrected step still fails, because the sdk build needs `acp-bridge` and `core` `dist/` that `--ignore-scripts` never produces

Reviewed at head `88c4becdaa`. The workspace specifier is now correct — `@qwen-code/sdk` is the package name in `packages/sdk-typescript/package.json`, and the install links `node_modules/@qwen-code/sdk -> ../../packages/sdk-typescript` — so the `No workspaces found` failure from our previous comment is genuinely fixed. But the step still cannot succeed in this job, so the publish job stays broken; it now fails one step earlier than before.

**Where** — `.github/workflows/live-host-release.yml:361-362`, the new `Build dependencies (sdk)` step in the `publish` job.

**Trigger** — the job's own install step at line 359, `npm install --ignore-scripts`. `dist` is git-ignored (`.gitignore:72`) and is only ever produced by build scripts, so with lifecycle scripts disabled **no package in the tree has a `dist/`**. Nothing else in the job supplies one: the source is checked out fresh at line 349-350, and the artifacts downloaded from the `build` job land in `release-assets/` (lines 284-287) and contain only `packages/live-host/release/*.dmg`, `*.zip`, `*-manifest.json` (lines 261-267).

`@qwen-code/sdk`'s build resolves its sibling imports through their `exports` maps, and every one of them points into `dist/`:

- `packages/acp-bridge/package.json` maps `./mcpTimeouts`, `./channelControlTimeouts`, `./daemonEventTypes`, `./bridgeTypes`, `./transcriptReplay` to `./dist/*.js` + `./dist/*.d.ts`
- `packages/core/package.json:16-19` maps `./transcriptRecords` to `./dist/src/utils/transcript-records.{js,d.ts}`

**Reproduction** — clean room outside any other checkout (so nothing can resolve upward into a built tree), at this head, running the job's two steps verbatim:

```text
$ git archive 88c4becdaa | tar -x -C /tmp/rv10836-ci && cd /tmp/rv10836-ci
$ npm install --ignore-scripts --no-audit --progress=false
added 2122 packages in 20s                      # exit 0
$ ls -d packages/*/dist
ls: cannot access '/tmp/rv10836-ci/packages/*/dist': No such file or directory
$ npm run build --workspace @qwen-code/sdk

> @qwen-code/sdk@0.1.8 build
> node scripts/build.js

src/daemon/DaemonClient.ts(10,8): error TS2307: Cannot find module '@qwen-code/acp-bridge/mcpTimeouts' or its corresponding type declarations.
src/daemon/DaemonClient.ts(11,52): error TS2307: Cannot find module '@qwen-code/acp-bridge/channelControlTimeouts' or its corresponding type declarations.
src/daemon/events.ts(32,8): error TS2307: Cannot find module '@qwen-code/acp-bridge/daemonEventTypes' or its corresponding type declarations.
...
npm error Lifecycle script `build` failed with error:
npm error workspace @qwen-code/sdk@0.1.8
                                                # exit code 1
```

88 tsc errors in total. The six distinct root causes are all TS2307 on unbuilt siblings — `@qwen-code/acp-bridge/{mcpTimeouts, channelControlTimeouts, daemonEventTypes, bridgeTypes, transcriptReplay}` and `@qwen-code/qwen-code-core/transcriptRecords` — and the other ~80 are downstream fallout from those types collapsing (e.g. `Property 'requestId' does not exist on type 'DaemonSessionUpdateData | ...'`). `scripts/build.js:38` runs `tsc --project tsconfig.build.json` first, so the step dies there; if tsc were satisfied the esbuild bundles would fail on the same specifiers — I reproduced that variant separately and it reports `Could not resolve "@qwen-code/acp-bridge/daemonEventTypes" … The module "./dist/daemonEventTypes.js" was not found on the file system`.

**Impact** — the PR's stated goal (let the qwen-live build resolve `@qwen-code/sdk`) is not achieved, and the failure is invisible to CI: the `publish` job is gated on `github.event_name == 'workflow_dispatch' && inputs.dry_run == false && github.repository == 'QwenLM/qwen-code'` (line 273), so no PR lane ever runs it. It merges green and only breaks at the next real Live Host release — and inside that job the GitHub release creation, asset upload and stable-feed update (lines 293-347) all happen **before** the npm publish steps, so a run would publish the Host release and then fail to publish `@qwen-code/qwen-live`, leaving the two out of sync.

**Fix direction** — the sdk cannot be built in isolation here; its dependency chain has to be built first, in the repo's own order (`scripts/build.js` lists `packages/core` → `packages/acp-bridge` → `packages/sdk-typescript`):

1. add explicit build steps for `@qwen-code/qwen-code-core` and `@qwen-code/acp-bridge` ahead of the sdk step; or
2. drop `--ignore-scripts` from line 359 so the workspace `prepare` builds the tree, the way this workflow's own `build` job does with a plain `npm ci` (line 111); or
3. copy the proven release pattern — `npm ci --ignore-scripts` → `npm run postinstall` → `npm run generate` → root `npm run build` (`release.yml:386-392` and `:429`), which replays the root postinstall and codegen precisely because `--ignore-scripts` also skips `packages/core`'s own `postinstall`.

Options 2 and 3 are heavier than one workspace build, and this job carries a shared `timeout-minutes: 20` (line 278) that already covers release creation and uploads, so whichever variant you pick is worth timing once against a dispatch dry run.

Our APPROVED at 15:27Z on this same head was wrong: it verified that the corrected specifier resolves, not that the build it runs can succeed. This review supersedes that approval.

---

中文：workspace 名称已修正（`@qwen-code/sdk`），上一条评论中的 `No workspaces found` 确实解决了；但该步骤在这个 job 里仍然无法成功。`publish` job 用 `npm install --ignore-scripts` 安装，而 `dist` 既不在 git 里（`.gitignore:72`）也不会被构建，所以整棵树没有任何 `packages/*/dist`；job 后续也没有别的来源（源码是 349-350 行重新 checkout 的，从 `build` job 下载的产物只落在 `release-assets/`，内容是 dmg/zip/manifest）。而 sdk 的构建要通过 `exports` 解析 `@qwen-code/acp-bridge/*` 和 `@qwen-code/qwen-code-core/transcriptRecords`，这些映射全部指向 `dist/`。在干净环境按 job 原样执行两步复现：`npm run build --workspace @qwen-code/sdk` 退出码 1，共 88 个 tsc 错误，其中 6 个 TS2307 是根因，其余是类型塌缩后的连带错误。因此发布任务依旧失败，只是失败点从 qwen-live 构建提前到了新增步骤；又因为该 job 只在 `workflow_dispatch` 下运行，PR CI 发现不了，会在下次真实 Live Host 发布时才暴露——而且那时 GitHub release 与 stable feed 已经在同一 job 的更早步骤里更新完了，会出现 Host 发布成功、npm 包未发布的不同步。修复方向：先按仓库依赖顺序构建 `core` → `acp-bridge` → `sdk`；或去掉 `--ignore-scripts`；或沿用 `release.yml` 的 `npm ci --ignore-scripts` + `npm run postinstall` + `npm run generate` + 根 `npm run build`。我们 15:27Z 在同一 head 上的 APPROVED 有误（只确认了 specifier 能解析，未验证构建能通过），本条评审取代该批准。

**Review by qqqys — APPROVED** [review]

**Review by DragonnZhang — APPROVED** [review]
