### PR TITLE
chore(desktop): drop stale packages/desktop references after Electron removal

### PR DESCRIPTION
**Pull request by yiliang114**
## What this PR does

Follow-up cleanup to #9085, which removed the Electron desktop package. A few references to the deleted tree survived in CI tooling and docs, and this PR removes or corrects them:

- The triage flakiness gate still special-cased `packages/desktop/*` as an out-of-workspace tree that must be skip-logged. With the package gone that case arm can never match, so it is reduced to the still-existing `docs-site/*` tree, and a stale inline comment using the Electron package as the "unsupported runner family" example is reworded.
- The gate's behavioral test built its fixture around `packages/desktop/apps/electron/*`. The test now covers only the remaining real case (docs-site with a vitest config that must not be collected). The historical comment about the round-6 desktop misclassification goes with it since the scenario it described no longer exists in the repo.
- The Web Shell favicon comment pointed at the deleted `packages/desktop/apps/webui/.../favicon.svg`; it now points at the surviving copy of the same purple Qwen mark in the Tauri shell's bootstrap assets.
- Two project skill references (`repo-hygiene`, `find-simplifications`) are updated from the old Electron layout (`packages/desktop/`, `desktop/apps/electron`, `desktop/apps/viewer`) to the Tauri `packages/desktop-shell/`.

## Why it's needed

Dead references to a removed package mislead future maintainers: the gate's skip arm implies a tree exists that doesn't, the test fixture asserts behavior for a package that can never reappear, and docs point at files that were deleted. None of this breaks CI today — it is purely misleading residue from the removal.

### How to verify

- Confirm the gate change is semantics-preserving for every tree that still exists: `git grep "packages/desktop" -- .github/workflows/qwen-triage.yml .github/scripts/qwen-triage-workflow.test.mjs` returns nothing, and `docs-site/*` files still hit the same skip arm with the same reason string.
- Run the gate's test suite: `node --test .github/scripts/qwen-triage-workflow.test.mjs`. On Linux (CI) all suites should pass. Note for local runs: the two "behavioral, under the production wrapper" suites are Linux-specific and fail on macOS both before and after this change (verified: 76 pass / 42 fail on macOS with and without the change; the rewritten docs-site test fails locally with the identical `'error' !== 'n/a'` environmental verdict as the test it replaces).

### Evidence (Before & After)

N/A (CI config and docs only, no user-visible change)

### Tested on

|     OS     | Status |
| :--------: | :----: |
|  🍏 macOS  |   ✅   |
| 🪟 Windows |   ⚠️   |
|  🐧 Linux  |   ⚠️   |

### Environment (optional)

N/A

## Risk & Scope

- Main risk or tradeoff: a PR branched before the Electron removal that still touches `packages/desktop/**` would now fall through to the generic resolver instead of the dedicated skip arm; such a branch conflicts with main anyway and must be rebased first.
- Not validated / out of scope: Windows and Linux local runs (covered by CI); historical design/plan docs under `docs/` intentionally keep their references as historical record.
- Breaking changes / migration notes: none.

## Linked Issues

- Follow-up to #9085
- Related to #8596

<details>
<summary>中文说明</summary>

## 本 PR 做了什么

#9085 删除 Electron 桌面包之后的跟进清理。CI 工具和文档中仍残留对已删除目录的引用，本 PR 将其移除或更正：

- triage 抖动门禁（flakiness gate）仍把 `packages/desktop/*` 作为"不在 npm workspace 安装集内、必须跳过"的特例处理。包已删除，该分支永远不会命中，因此缩减为仍然存在的 `docs-site/*`，并把一处以 Electron 包举例"不支持的 runner 家族"的过时注释改写。
- 门禁的行为测试用 `packages/desktop/apps/electron/*` 构造 fixture。现在只覆盖仍然真实存在的场景（带 vitest 配置但不应被收集的 docs-site）。描述 round-6 桌面测试误判的历史注释一并移除，因为它描述的场景在仓库中已不存在。
- Web Shell favicon 注释原来指向已删除的 `packages/desktop/apps/webui/.../favicon.svg`，现指向 Tauri shell bootstrap 资源中保留的同款紫色 Qwen 标志。
- 两个项目 skill 文档（`repo-hygiene`、`find-simplifications`）从旧的 Electron 目录结构（`packages/desktop/`、`desktop/apps/electron`、`desktop/apps/viewer`）更新为 Tauri 的 `packages/desktop-shell/`。

## 为什么需要

对已删除包的无效引用会误导后续维护者：门禁的跳过分支暗示一个已不存在的目录树，测试断言的是一个不可能再出现的包的行为，文档指向已删除的文件。这些目前不会破坏 CI——纯粹是删除操作留下的误导性残留。

## 评审验证

- 确认门禁改动对现存目录树语义不变：`git grep "packages/desktop" -- .github/workflows/qwen-triage.yml .github/scripts/qwen-triage-workflow.test.mjs` 应无输出；`docs-site/*` 文件仍以相同的 reason 字符串命中同一跳过分支。
- 运行门禁测试：`node --test .github/scripts/qwen-triage-workflow.test.mjs`。Linux（CI）上应全部通过。注意：两个"behavioral, under the production wrapper"套件是 Linux 专用的，在 macOS 上改动前后同样失败（已验证：改动前后均为 76 通过 / 42 失败；改写后的 docs-site 测试本地失败原因与被替换的旧测试完全相同，均为环境性的 `'error' !== 'n/a'`）。

</details>

### CODE REVIEW

**Comment by yiliang114** [comment]
CI note: the failing `Test (ubuntu-latest)`, `Capture web-shell visuals`, and `web-shell E2E Smoke` jobs all fail at `npm ci` → `tsc --build` with `error TS1117` in `packages/cli/src/ui/hooks/session-swap-telemetry.test.ts` (duplicate `getSessionDisplayName` / `getCurrentCustomTitle` object-literal properties). This is pre-existing breakage on `main` from a semantic merge conflict between #9994 and #9998 — unrelated to this PR's diff. Fix is already open as #10022; once it merges, rebasing this branch should turn CI green.

**Review by chiga0 — DISMISSED** [review]
**Checked and approved** — no blockers.

---

**CI**

- `Test (ubuntu/macos/windows-latest, Node 22.x)`: 🔄 in progress at review time
- `Capture web-shell visuals (ubuntu-latest)`: 🔄 in progress
- `Desktop Shell (ubuntu/windows)`: ✅ pass
- `Dependency CVE audit` + `Secret scan`: ✅ pass
- `Integration Tests`: ⏭ SKIPPED (path filter)

---

**What I verified**

**`packages/desktop` is gone.** Only `packages/desktop-shell` exists on main — confirmed via the contents API. No `packages/desktop` references remain in `qwen-triage.yml` at this head.

**Gate change — semantic preservation:**
- `docs-site/*` arm is intact at line 3562 with the identical `add_skip` call and reason string.
- The removed `packages/desktop/*|docs-site/*` combined arm is the only change to case dispatch; the `has_vitest_config` skip path (line 3577) is unchanged.
- Fallthrough for a hypothetical stale `packages/desktop/**` file (pre-rebase branch) is the acknowledged trade-off and is correctly scoped: such a branch conflicts with main and must be rebased regardless.

**Test rewrite — non-vacuous:**
The new fixture (`docs-site/package.json` + `docs-site/vitest.config.js` + `docs-site/b.test.ts`) exercises the `docs-site/*` arm directly. The `counts("b.test.ts") === 0` assertion would fail if the arm were removed — the file would reach the generic resolver, `vitest.config.js` would be found, and the test would be invoked, changing `flake_verdict` away from `n/a`. The presence of `vitest.config.js` in the fixture is a deliberate stress: it confirms the explicit skip arm fires before the config-check resolver, which is the exact behavior the original test was guarding.

**Favicon comment:** `packages/desktop-shell/bootstrap/qwen-code-logo.svg` exists on main (933 bytes). The reference is valid.

**Skill docs:** `find-simplifications` and `repo-hygiene` reference updates are factually correct — `packages/desktop` removed from exclusion lists, consumer count updated from four to three, ui-apps description reflects Tauri.

---

_Reviewed with AI assistance._

**Review by chiga0 — APPROVED** [review]
No blocking findings.

**Prior round:** Round 1 reviewed head `1108d3c7` — approved, dismissed when new commits were pushed. No prior findings to re-evaluate.

**What changed since round 1:** New commits to `scripts/tests/no-ak-integration-ci.test.js` strengthening the PowerShell `$temp` block wiring assertions to be contiguous-block and ordering-aware (addressing bot suggestions from R3–R5 iterations).

**Checked:**
- Gate change (`qwen-triage.yml`): removing `packages/desktop/*|` from the skip arm is correct — that tree was deleted in #9085. Files from `packages/desktop-shell` fall through to the generic resolver, where `has_vitest_config` handles them correctly (it is a Tauri shell with no vitest config, so it hits the unsupported-runner-family skip arm as expected).
- Test mirrors gate change (`qwen-triage-workflow.test.mjs`): the rewritten test covers only the remaining real case (docs-site with a vitest config that must not be collected). Assertions are correct.
- Favicon comment path: confirmed `packages/desktop-shell/bootstrap/qwen-code-logo.svg` exists at head (933 bytes).
- No remaining `packages/desktop` references in `qwen-triage.yml` at head.
- `no-ak-integration-ci.test.js` improvements: the contiguous-block assertion pins the 4-line `$temp` block as ordered; `expect(redirectTempIndex).toBeLessThan(windowsJob.indexOf("name: 'Run tests and generate reports'"))` closes the prior R5-1 ordering gap.
- Doc/skill updates (find-simplifications, repo-hygiene): consistent with the Electron → Tauri migration.

**CI:** `Test (ubuntu-latest, Node 22.x)` green. `Test (windows-latest, Node 22.x)` and `Test (macos-latest, Node 22.x)` SKIPPED — expected per PR description (behavioral tests are Linux-specific; author confirmed macOS result is identical before/after this change). `Integration Tests (CLI, No Sandbox)` SKIPPED — no runtime CLI changes in this PR.

**Not covered:** No toolchain in this environment, so execution rungs 1–3 not run. Windows/macOS platform behavior unverified (SKIPPED in CI).

_Reviewed with AI assistance._
