### PR TITLE
feat(autofix): stop a PR that fails to push for N rounds in a row

### PR DESCRIPTION
**Pull request by wenshao**
## What this PR does

Adds a **consecutive-failure** sub-cap, separate from the total round cap, so a PR that fails to push every round stops instead of retrying up to 100 times under takeover.

## Why it's needed

The round cap answers "how many **productive** rounds may a PR take?" — and takeover raises it to 100 deliberately, for PRs that need many rounds of address-feedback-then-push. It does not answer "how many rounds may fail **in a row**?"

Observed on **#6723** (a 5700-line, 47-file, 5-day-old PR that conflicts with a fast-moving `main`):

| round | outcome |
| --- | --- |
| 1 | gate rejection — `tests failed in packages/core` |
| 2 | agent **timeout (50 min)** |
| 3 | agent **timeout (50 min)** |
| 4 | gate rejection — `tests failed in packages/cli` |
| 5 | gate rejection — push rejected, tests failed |
| 6 | agent **timeout (50 min)** |
| 7 | gate rejection — `tests failed` |

Seven straight failures over eight hours, **nothing pushed**, heading for round 100 — each round a ~50-minute agent run or a full gate cycle. Every round re-resolves a conflict the agent cannot finish inside the budget, or produces a fix that breaks tests. Retrying at the same per-round budget does not converge; a human has to rebase or split the PR.

The two failure kinds are handled elsewhere individually (a timeout, a gate rejection), but nothing notices that they are happening **back to back with no progress**.

## How

`CONSECUTIVE_FAILURE_CAP: '5'`, distinct from `TAKEOVER_MAX_ROUNDS: '100'`.

Reaching the handoff step at all means this round did **not** push — the push and no-op paths report from a different step. So the step counts the unbroken run of prior failure markers by walking the bot's own eval-comment headlines newest-first and **stopping at the first that pushed** (`Addressed the latest review feedback`) **or was a deliberate no-op** (`no changes needed`) — either proves the loop was making progress, so the streak resets there. If the run (this round included) reaches the cap, it forces the terminal round **even under takeover**, with a handoff that names the actual fix: rebase / split / reduce the PR, then `@qwen-code /retry` to re-arm.

It is **cause-agnostic**: a timeout and a gate rejection both count, because both are "failed, nothing pushed." A single push or no-op anywhere in the run resets it, so this only ever fires on a genuinely stuck PR.

### How to verify

1. `npx vitest run scripts/tests/qwen-autofix-workflow.test.js` — 92/92 (a run in three hits the pre-existing `takeover-command toggle` load flake; see Risk). The new test **replays the real extracted counter+override block** under bash, with a stubbed `gh` serving a synthetic comment history:

   | prior markers | streak (incl. this round) | terminal? |
   | --- | --- | --- |
   | *(none)* | 1 | no |
   | 4 × failure | 5 | **yes** — structural handoff, mentions `/retry` |
   | 3 × failure | 4 | no |
   | fail, fail, **push**, fail, fail | 3 | no (push reset it) |
   | 5 × fail, **no-op**, fail | 2 | no (no-op reset it) |
   | fail, **timeout**, fail, **timeout** | 5 | **yes** (cause-agnostic) |

2. Mutation-verified, four reverts each turning it red: neutering the override; making a no-op not reset; making a push not reset; setting the cap equal to the takeover cap (so it never binds).

3. One existing test needed its extraction anchor updated: `retries a verification-gate crash` grabbed the decision block by its trailing `fi` + report `{`, which this block now sits between. It now anchors on the new block's comment, so it drives only the crash decision — unchanged behaviour, no `gh` call.

4. Static, run locally with the exact CI toolchain: `js-yaml` parses; all 37 `run:` blocks pass `bash -n`; actionlint 1.7.12 clean; prettier clean.

5. Post-merge smoke: #6723's next scan should post the structural handoff and go terminal instead of a 8th failed round.

### Evidence (Before & After)

```
BEFORE  #6723: 7 straight failures (timeouts + gate rejections), 8h,
        heading for round 100 — ~50 min of agent time each

AFTER   at 5 in a row: terminal handoff — "rebase, split, or reduce it,
        then comment @qwen-code /retry" — and future scans skip it
```

### Tested on

|     OS     | Status |
| :--------: | :----: |
|  🍏 macOS  | ✅ tested |
| 🪟 Windows | N/A |
|  🐧 Linux  | ⚠️ CI |

## Risk & Scope

- Main tradeoff: a PR that genuinely needs 6+ **failing** rounds to eventually succeed now stops at 5 and asks for a human. That is the intended tradeoff — 5 consecutive failures with nothing pushed is a strong signal the per-round budget is the wrong tool — and `/retry` re-arms it after the human intervenes, opening a fresh window.
- Only fires in the handoff step, which already runs only on a non-pushing round; a healthy iterating PR (push, or a legitimate no-op) never accumulates a streak.
- One extra `gh api …/comments` fetch per failing round. On the fetch failing, `PRIOR_HEADS` is empty and the streak is 1 — so an API blip cannot force a spurious terminal (fail-open).
- Pre-existing and unrelated: `takeover-command toggle` fails under full-suite subprocess load — A/B on this machine shows unmodified `main` failing the same test at a comparable rate, and it passes in isolation.
- Not in scope: the opposite asymmetry — a crash *before* reading feedback goes terminal after ONE round (observed on #7458), which may be too aggressive for a transient blip. That is a separate change; `/retry` recovers it today.
- Breaking changes / migration notes: none.

## Linked Issues

Found while analysing why #6723 had burned 7 agent rounds under takeover with nothing pushed. Part of the autofix-reliability line: #7330, #7351, #7368, #7412, #7416, #7438.

<details>
<summary>中文说明</summary>

## 本 PR 做了什么

新增一个**连续失败**子上限,独立于总轮次上限,让"每轮都推送失败"的 PR 停下来,而不是在 takeover 下一路重试到 100。

## 为什么需要

轮次上限回答的是"一个 PR 可以用多少**有产出**的轮次",takeover 特意把它提到 100,是给需要多轮"处理反馈→推送"的 PR。它没有回答"可以**连续**失败多少轮"。

在 **#6723**(5700 行、47 文件、跑了 5 天、与飞速前进的 `main` 冲突)上实测:7 轮全败(3 次 agent 超时 50 分钟、4 次门拒绝——修复过不了测试),历时 8 小时**零推送**,正冲着 round 100 去,每轮要么 50 分钟 agent 运行、要么一整轮门检查。每轮都在重解一个解不完/过不了测试的冲突。以相同的单轮预算重试不会收敛,只能靠人 rebase 或拆分。

两类失败(超时、门拒绝)各自都有处理,但**没有任何机制注意到它们正在背靠背、毫无进展地连续发生**。

## 怎么做

`CONSECUTIVE_FAILURE_CAP: '5'`,独立于 `TAKEOVER_MAX_ROUNDS: '100'`。

能走到交接步骤,本身就意味着这一轮**没有推送**(推送与 no-op 路径从另一个步骤汇报)。于是该步骤统计"未被打断的连续失败":倒序遍历 bot 自己的 eval 评论标题,遇到第一个**推送**(`Addressed the latest review feedback`)或**合法 no-op**(`no changes needed`)即停——两者都证明循环在推进,连续计数在此重置。若这条连续段(含本轮)达到上限,即使在 takeover 下也强制终态,并给出真正的修复指引:rebase/拆分/精简该 PR,再 `@qwen-code /retry` 重新武装。

它**不区分成因**:超时和门拒绝都算"失败且未推送"。连续段中任意一次推送或 no-op 都会重置它,因此只会在真正卡住的 PR 上触发。

## 评审验证

1. `npx vitest run scripts/tests/qwen-autofix-workflow.test.js` —— 92/92。新测试在 bash 下**回放真实提取的计数+override 块**,用桩 `gh` 喂合成评论历史,覆盖 6 种组合(见上方英文表格:无历史=1 不终态;4 败+本轮=5 终态;3 败+本轮=4 不终态;推送重置;no-op 重置;超时与门拒混合仍达 5 终态)。
2. 变异验证,四处回退各自变红:令 override 空转;令 no-op 不重置;令推送不重置;把阈值设成 takeover 上限(使其永不生效)。
3. 一个既有测试需更新提取锚点:`retries a verification-gate crash` 原来靠"结尾 `fi` + 报告 `{`"抓取决策块,而本块正插在两者之间。现改为锚定本块的注释,只驱动 crash 决策——行为不变,不调用 `gh`。
4. 静态(均用 CI 一致工具):YAML 可解析;37 个 `run:` 块过 `bash -n`;actionlint 1.7.12 clean;prettier clean。
5. 合并后冒烟:#6723 下一次扫描应给出结构性交接并终态,而不是第 8 轮失败。

## 风险与范围

- 主要权衡:一个确实需要 6+ 轮**失败**才最终成功的 PR,现在会在第 5 轮停下并请人介入。这正是预期权衡——连续 5 轮零推送强烈说明单轮预算是错的工具——人介入后 `/retry` 会重新武装、开启新窗口。
- 只在交接步骤触发,而该步骤本就只在"未推送"的轮次运行;健康迭代的 PR(推送或合法 no-op)永远不会累积连续段。
- 每个失败轮多一次 `gh api …/comments`。拉取失败时 `PRIOR_HEADS` 为空、连续数为 1——因此一次 API 抖动不会误判终态(fail-open)。
- 既有且无关:`takeover-command toggle` 在全量子进程负载下失败——本机 A/B 显示未修改的 `main` 以相当频率红同一测试,单独跑通过。
- 不在范围内:反向的不对称——读反馈**之前**崩溃会在**一轮**后即终态(见 #7458),对瞬时抖动可能过于激进。那是另一个改动;目前靠 `/retry` 恢复。
- 破坏性变更:无。

## 关联 Issue

在分析 #6723 为何在 takeover 下烧掉 7 个 agent 轮次却零推送时发现。属 autofix 可靠性主线:#7330、#7351、#7368、#7412、#7416、#7438。

</details>

### CODE REVIEW

**Comment by wenshao** [comment]
@qwen-code /takeover

**Comment by wenshao** [comment]
## Code review — consecutive-failure sub-cap

Verified the mechanics by extracting the new block from the PR head and replaying it under `bash` (the added test passes, 92/92 with the one flake noted): the streak walk is correct — `CONSEC_FAIL` = 1 (this round) + trailing prior failures since the last progress marker, reset to 1 at each push / no-op; the window filter (`win=<key>` first, legacy no-`win=` fallback) is right; `ic.json` is fetched in `Prepare branch and feedback` *before* this round's marker is posted, so there's no double-count; and every path that reaches the breaker (`NEWEST` set → `ic.json` exists → `cat`) means the `gh api` fallback and the fail-open-to-`CONSEC_FAIL=1` path are pure belt-and-suspenders. Nice, tight change. A few things worth a second look:

### 1. It silently overrides the "transient model error keeps the full budget" decision right above it

The breaker is cause-agnostic, and the mixed-cause test confirms `🤖 AutoFix could not reach the model (attempt …)` headlines count toward the streak. But the sibling block a few lines up (the `CAUSE_MAX` logic) *deliberately* gives a **transient** (non-auth) model error the full `MAX_ROUNDS` budget:

```
# A transient 429/5xx self-heals, so it keeps the full round budget.
CAUSE_MAX="${MAX_ROUNDS}"
if [[ "${API_ERROR_KIND}" == 'auth' && ... ]]; then CAUSE_MAX="${API_AUTH_MAX_ROUNDS}"; fi
```

That path produces a non-terminal RETRY headline (`MARK_ROUND < MAX_ROUNDS`), so the new breaker runs on it and can force it terminal at 5. Net effect: a model-provider outage that spans ≥5 scan cycles now marks the PR terminal and requires a human `@qwen-code /retry`, where before it would self-heal once the provider recovered — and because an outage hits every in-flight autofix PR at once, they all go terminal together. The Risk section covers the "genuinely needs 6+ *failing* rounds to eventually succeed" tradeoff, but not this transient-outage case, which is a different animal (the failures aren't the PR's fault and *do* self-heal).

Two clean resolutions — either is fine, but it's worth a conscious call:
- **Accept + document** it in the Risk section (5 wasted agent runs during an outage is itself expensive, so capping is defensible).
- **Exempt the self-healing branch**: don't count a round whose cause is the transient model-reach path (you already have `API_ERROR_KIND` / the `could not reach the model` headline to key on), so provider blips still auto-recover while a genuinely stuck PR still trips the cap.

### 2. The reset detector ↔ emit-headline coupling is untested

The reset keys on the literal substrings `"Addressed the latest review feedback"` and `"no changes needed"`, but the *emitters* of those headlines (in `Push and report`) aren't pinned by any test — the new test uses its own `PUSH`/`NOOP` literals, and a repo-wide grep shows those strings appear nowhere else in `scripts/`. So if either headline is ever reworded without updating the detector, the reset silently stops firing and **every** takeover PR marches to the cap while pushing healthily each round — a false-terminal, which is the dangerous direction. Cheap hardening: have the test assert the workflow's actual `Push and report` emit lines `contains(...)` these substrings (or key the push reset on the structured `acted=true` marker, which is drift-proof; no-op still needs the substring since it shares `acted=false` with failures).

### 3. Minor

- The walk relies on GitHub returning issue comments oldest-first without an explicit sort, whereas sibling blocks in this file `sort_by(.created_at)` when order matters. It's safe in practice (the REST default is ascending), just an inconsistency — a stray reorder would corrupt the streak count silently.
- The Risk note "One extra `gh api …/comments` fetch per failing round" is actually pessimistic: in `review-address` `ic.json` always exists by the time this step runs, so it's a `cat`, not a fetch — zero extra API calls on the normal path. Good, just worth correcting the note.

Correctness, fail-open behavior, window scoping, and test fidelity (real extracted block replayed under bash) all check out. #1 is the only one I'd want resolved before merge; #2/#3 are hardening.

**Review by yiliang114 — APPROVED** [review]
LGTM. Clean circuit breaker design — the transient-error exemption is well-reasoned (provider outage must not mass-terminate PRs), and the streak reset on push/no-op is correct. Test coverage is exceptional: 10+ cases including window filtering, auth vs transient distinction, and pinning the reset substrings to actual emit lines.
