### PR TITLE
docs(autofix): require evidenced pre-commit verification, not a bare "verified"

### PR DESCRIPTION
**Pull request by wenshao**
## What this PR does

Turns the autofix agent's pre-commit verification from a soft "run the checks" into an evidenced, hard requirement: actually run them, don't commit if they fail, and record each command and its result.

## Why it's needed

The skill already told the agent to run `build`/`typecheck`/`lint`/focused Vitest before committing. But it was soft, and a self-assessment is not a fact.

**#7408** committed a fix with a real TypeScript error:

```
src/daemon/session/DaemonSessionProvider.test.tsx(6410,44):
  error TS2554: Expected 1 argument
```

The verification gate caught it and rejected the round — but the agent's own summary for that round claimed *"verified all 3 commits at HEAD `a52458a8`"*. A bare "verified" stood in for actually running `typecheck`, and the gate rejection discarded the whole round (~a full agent run). Most `tests failed` gate rejections across the fleet share this shape: the commit could have been held back by the agent running the same command the gate was about to.

This is the **checkable** half of "audit before committing." The undirected / reverse-audit-until-clean practice does not transfer to an unsupervised agent — it has no verifiable stopping condition, the self-audit is unreviewed, and more self-checking worsens the timeouts already seen on large PRs (#6723). "Run the gate's own checks first and show the evidence" does transfer, because the gate is the objective signal and the evidence is auditable.

## How

The `address-review` outcome and the shared rule now require:

- **Actually run** `build`/`typecheck`/`lint`/touched-package Vitest — "do not assert them from reading the diff."
- If `typecheck` or a touched-package test **fails, do NOT commit** — treat the feedback as unresolved and write `failure.md`.
- End `address-summary.md` with a **`## Verification`** section listing **each command run and its result** (e.g. `- npm run typecheck — passed`). A bare "verified" is explicitly not acceptable.

The framing is deliberately structural, not etiquette: the deterministic gate re-runs these exact commands and discards the round on any failure, so skipping them does not save time — it moves the rejection later and wastes the round. That rationale is in the prose so the requirement reads as "why," not "please."

No new work is added — those commands were already required; the change is that they must be run and evidenced, not claimed.

### How to verify

1. `npx vitest run scripts/tests/qwen-autofix-workflow.test.js` — 92/92 (a run in three hits the pre-existing `takeover-command toggle` load flake; see Risk). The new test pins the contract: run-don't-assert, no-commit-on-failure, the `## Verification` section, "each command … and its result," the explicit rejection of a bare "verified," and the gate-re-runs framing.
2. Mutation-verified: softening the summary requirement back to a bare "verified" turns the test red.
3. Static: prettier clean on the skill and the test (the skill passes `prettier --check` on `main` too, so nothing environmental).

### Evidence (Before & After)

```
BEFORE  skill: "run build/typecheck/lint/Vitest ... commit after they pass"
        #7408: committed a TS error, summary said "verified all 3 commits",
        gate rejected → round wasted

AFTER   "actually run them; if typecheck/tests fail, DO NOT commit;
         end the summary with ## Verification listing each command + result;
         a bare 'verified' is not acceptable"
```

### Tested on

|     OS     | Status |
| :--------: | :----: |
|  🍏 macOS  | ✅ tested |
| 🪟 Windows | N/A |
|  🐧 Linux  | ⚠️ CI |

## Risk & Scope

- This is a prompt change, not a gate — it cannot *force* the agent to run the commands. Its value is (a) making a false "verified" visible against the gate, and (b) nudging the agent to catch defects before the commit rather than after. The gate remains the actual enforcement; #7368 (merged) already feeds a gate rejection back so the next round fixes it.
- Deliberately NOT added: "multiple undirected / reverse audit rounds until no problems." That practice depends on human oversight and mutation-checking to know when to stop; an unsupervised agent given it either declares "no problems" prematurely (which is exactly #7408) or churns, and the extra rounds worsen large-PR timeouts. The checkable subset — re-read the diff adversarially, then run the gate's own checks and show the results — is what this PR adds.
- Pre-existing and unrelated: `takeover-command toggle` fails under full-suite subprocess load; unmodified `main` fails it at a comparable rate here and it passes in isolation.
- Breaking changes / migration notes: none.

## Linked Issues

Prompted by a maintainer asking whether the bot could be required to audit before committing. Part of the autofix-reliability line: #7368, #7438, #7482.

<details>
<summary>中文说明</summary>

## 本 PR 做了什么

把 autofix agent 的"提交前验证"从软要求("跑一下检查")变成**带证据的硬要求**:必须真的运行、失败则不提交、并逐条记录命令与结果。

## 为什么需要

skill 早就要求提交前跑 `build`/`typecheck`/`lint`/focused Vitest,但太软 —— 而**自评不是事实**。

**#7408** 提交了一个带真实 TS 错误的修复(`DaemonSessionProvider.test.tsx(6410,44): error TS2554`),门检查抓到并拒绝了整轮 —— 而 agent 那一轮的自述却写着*"verified all 3 commits"*。一句空洞的"verified"替代了真正运行 `typecheck`,门拒绝把整轮(约一次完整 agent 运行)作废。机群里大量 `tests failed` 的门拒绝都是同一形态:只要 agent 先跑一遍门即将跑的同一命令,这个提交本可以被拦下。

这是"提交前审计"里**可检查**的那一半。无方向/反向审计到没问题的做法**无法**搬到无监督 agent 上——它没有可验证的停止条件、自审无人复核,而且更多自审会加重大 PR 上已经出现的超时(#6723)。"先跑门自己的检查、并出示证据"是可以搬的,因为门是客观信号、证据可审计。

## 怎么做

`address-review` 的 outcome 与共享规则现在要求:

- **真的运行** `build`/`typecheck`/`lint`/改动包的 Vitest —— "不要靠读 diff 断言"。
- 若 `typecheck` 或改动包测试**失败,则不提交** —— 当作本轮未解决,写 `failure.md`。
- `address-summary.md` 以 **`## Verification`** 段收尾,逐条列出**跑了哪些命令、结果如何**(如 `- npm run typecheck — passed`)。空洞的"verified"明确不接受。

措辞刻意是结构性的而非礼节性的:确定性门会重跑这些完全相同的命令、任一失败即作废整轮,所以跳过它们并不省时间——只是把拒绝推迟、白费一轮。这个理由写在正文里,让要求读起来是"为什么",而不是"请"。

没有新增工作量——这些命令本就被要求;改变的是必须**运行并出示证据**,而非口头声称。

## 评审验证

1. `npx vitest run scripts/tests/qwen-autofix-workflow.test.js` —— 92/92。新测试钉住契约:运行而非断言、失败不提交、`## Verification` 段、"逐条命令与结果"、明确拒绝空洞"verified"、以及"门会重跑同一命令"的措辞。
2. 变异验证:把 summary 要求软化回空洞"verified"即变红。
3. 静态:skill 与测试均过 prettier(skill 在 `main` 上本就过 `prettier --check`,无环境问题)。

## 风险与范围

- 这是 prompt 改动而非门——无法**强制** agent 真的运行。它的价值在于:(a) 让虚假的"verified"在门面前暴露;(b) 促使 agent 在提交前而非提交后拦住缺陷。真正的强制仍是门;#7368(已合)已让门拒绝喂回下一轮去修。
- 刻意**不加**:"多轮无方向/反向审计直到没问题"。该做法依赖人监督与变异检验才知道何时停;无监督 agent 拿到它,要么过早宣布"没问题"(#7408 正是如此),要么空转,且额外轮次会加重大 PR 超时。可检查的子集——以评审者视角重读 diff、再跑门自己的检查并出示结果——才是本 PR 所加。
- 既有且无关:`takeover-command toggle` 在全量子进程负载下失败;本机未修改的 `main` 以相当频率红它,单独跑通过。
- 破坏性变更:无。

## 关联 Issue

由维护者提问"能否要求 bot 提交前审计"促成。属 autofix 可靠性主线:#7368、#7438、#7482。

</details>

### CODE REVIEW

**Comment by wenshao** [comment]
@qwen-code /takeover

**Comment by wenshao** [comment]
## Review — evidenced pre-commit verification

**Overview** — Turns the autofix skill's pre-commit verification from a soft "run the checks" into an evidenced hard requirement across three places: `Shared Rules`, `develop-issue` (step 9 / `e2e-report.md`), and `address-review` (`address-summary.md`). The agent must *actually run* `build`/`typecheck`/`lint`/touched-package Vitest, must not commit when `typecheck` or a touched-package test fails, and must end the summary with a `## Verification` section listing each command and its result — a bare "verified" is explicitly rejected. One new test pins the contract. 2 files, +59 / −14.

### Correctness / coherence — ✅
- The three edited sections are internally consistent. "Actually run, don't assert" + the gate-re-runs framing are stated once in Shared Rules and reinforced inline in `address-review`; `develop-issue` already carried the run-or-write-`failure.md` contract in step 6, so it correctly leans on Shared Rules + step 9's output requirement instead of duplicating the whole block.
- No contradiction with the existing environment-specific fallback: those rules are scoped to checks that *cannot* run locally ("An exact CI or Docker check that is not available on the current runner is not a failed runnable check"), while the new mandate targets the runnable build/typecheck/lint/Vitest set. The distinction is preserved.
- Replacing the freeform "verification results" with a structured `## Verification` section is a net improvement — no duplication introduced.

### Test coverage — ✅
- All seven assertions in the new test match the current head skill text, and the `.replace(/\s+/g, ' ')` flatten correctly bridges the ~78-col prose wraps.
- It tests **both** modes, not just `address-review`: the final assertion pins that `develop-issue`'s `e2e-report.md` also requires the Verification section (`section that lists each command you ran and its result (see Shared Rules)`).
- Non-vacuous and mutation-credible: `toContain('a bare "verified" is not acceptable')` goes red if the summary requirement is softened back, matching the stated mutation check.
- **No sibling-test breakage**: the two existing tests that assert `toContain('Run required verification commands before committing')` (≈ lines 2992, 3130) still pass — the reword kept that exact prefix and appended after it.

### Minor / nit (non-blocking)
- **Ordering ambiguity for the bilingual comment files.** Shared Rules says `address-summary.md` / `e2e-report.md` must "END with a complete collapsed Chinese translation of its content," while the new text says each should be "ending with a `## Verification` section." The intended reconciliation is clear — the *English body* ends with `## Verification`, then the collapsed `<details>中文说明>` (which itself includes the translated Verification section) is the true end of file — but it's left to inference. Since the whole point of the PR is to make the agent do the reliable thing, a half-clause would remove the last wiggle, e.g. *"the English body ends with `## Verification`, before the collapsed Chinese translation."*

### Risk — Low
Prompt-only; the deterministic gate remains the enforcement and this can't *force* the agent to run the commands. Value is exactly as framed: making a false "verified" visible against the gate and shifting defect-catching before the commit rather than after.

**Verdict: LGTM.** Coherent, well-scoped, and the test pins the contract on both modes without breaking siblings. The ordering nit is optional polish.

**Review by yiliang114 — APPROVED** [review]
LGTM. Well-motivated by the #7408 incident. The structural framing (gate re-runs → skipping only wastes a round) is much more effective than a soft 'please verify'. Test coverage pins all the key contract points thoroughly.

File: .qwen/skills/autofix/SKILL.md [hunk 1]
```diff
@@ -154,7 +160,9 @@ Implement the selected issue in the checked-out repository:
    Conventional Commit, e.g. `fix(core): summary (#<issue>)`.
 9. Write all required outputs:
    - `<workdir>/e2e-report.md` (bilingual per Shared Rules — it is posted
-     verbatim as a PR comment)
+     verbatim as a PR comment), ending with a `## Verification` section that
```
Comment (yiliang114) [inline .qwen/skills/autofix/SKILL.md:163]: The develop-issue mode mentions `## Verification` only in the step 9 output spec, but step 6 (where the agent actually runs the commands) has no reminder to record them. The agent may forget to log results between step 6 and step 9. Consider adding a brief note at the end of step 6: "record each command and its result for the Verification section in step 9". The address-review path has this covered with the explicit example format, but develop-issue does not.
