### ISSUE TITLE
fix(core): `tools.eager` entry named after an Object.prototype key crashes PermissionManager.initialize (from #10098 round-4 rescan)

### ISSUE THREAD

**Issue by yiliang114** [QwenLM/qwen-code#10400]
Follow-up from PR #10098 ("fix(core): decouple permissions.allow from tool registration via tools.eager (#10075)"), round-4 bot rescan at head `4a5130495ab1fe6f2889aba5a57eee1ccb4d39e4`. The PR is scope-fused (1544 additions > 1500 budget), so these verified findings are tracked here instead of landing in the PR this round. Source threads: R3-9, R3-2, R3-3, R4-9, R4-20, R2-17.

## 1. Critical (R3-9): unknown-entry warning loop crashes `PermissionManager.initialize()`

`tools.eager: ["constructor"]` — or any entry named after an `Object.prototype` key (`toString`, `valueOf`, `hasOwnProperty`, `isPrototypeOf`, `propertyIsEnumerable`, `toLocaleString`, `__proto__`) — throws inside `initialize()`, and `config.ts:3442` calls it without try/catch, so it is a CLI startup crash.

Code path at head:
- `resolveToolName` (`packages/core/src/permissions/rule-parser.ts:310`) is `TOOL_NAME_ALIASES[rawName] ?? rawName`; `TOOL_NAME_ALIASES` is a plain object literal (`rule-parser.ts:49`), so `TOOL_NAME_ALIASES['constructor']` returns the inherited `Object.prototype.constructor` **function** — not `undefined`, so `??` never falls back.
- `parseRule` (`rule-parser.ts:383-394`) returns that non-string `toolName` with `invalid` unset for a no-paren entry.
- In the unknown-entry loop added by `343a4dfc` (`permission-manager.ts:280-284`), `rule.toolName in TOOL_NAME_ALIASES` coerces the function key to its source string and evaluates `false` (no short-circuit), then `rule.toolName.startsWith('mcp__')` throws `TypeError: rule.toolName.startsWith is not a function`.

This contradicts the PR's own "unusable entries are dropped with a warning, never crash initialize()" contract — every other unusable-entry class is merely warned. Fix sketch: treat a resolved non-string `toolName` as a dropped (warned) entry, and test own properties only (`Object.hasOwn(TOOL_NAME_ALIASES, ...)`); note `Object.hasOwn` alone is not sufficient — `resolveToolName` must also stop returning the inherited prototype value (or the loop must re-check `typeof rule.toolName === 'string'`). Add a regression case `eagerTools: ['constructor']` asserting `initialize()` does not throw.

## 2. Doc accuracy (R3-2): "use permissions.deny to remove a tool outright" is false for MCP tools

`docs/users/configuration/settings.md:367` (tools.core row, added by `f1b47a048`) says "use `permissions.deny` to remove a tool outright" immediately after naming the bypassing families (MCP, skill). The sibling sentence at `settings.md:490` says "`permissions.deny` removes tools entirely". Both are false for MCP tools: MCP tools register via `mcp-client.ts:648/1488` → `ToolRegistry.registerTool` (`tool-registry.ts:289`), which only applies `isToolDisabled` (the `tools.disabled` set, `tool-registry.ts:265`) and never consults `PermissionManager`. A whole-tool-denied `mcp__*` tool stays registered, stays in `/tools` and the initial declarations, and is rejected only at call time — while `getToolRegistrationStatus` reports `'disabled'` for it. The PR's own SDK JSDoc (`sdk-typescript/src/types/types.ts`) says "MCP tools are exempt from deny-based removal — hide them with the per-server excludeTools / tools.disabled filters instead". Suggested wording (from the thread): "use `permissions.deny` to block a tool's calls (for MCP tools it stays listed and is rejected at runtime), or `tools.disabled` / the per-server `excludeTools` filter to remove it from the registry outright" — applied to both :367 and :490.

## 3. Doc accuracy (R3-3): ToolSearch-absent caveat omits two code-implemented carve-outs

The caveat added by `1a5c63736` (`sdk-typescript/src/types/types.ts:414-418`) says demoted tools "are out of reach for that session and a warning is logged" — absolute, but the code implements two carve-outs:
- (a) **Resumed sessions**: `revealDeferredToolsReferencedInHistory` runs before the withholding check at both call sites in `client.ts`, and `resolveDeferredToolsForReminder` skips already-revealed tools from `withheld` (`isDeferredToolRevealed` check), so a demoted tool referenced in resumed history gets its schema re-sent and is never warned about.
- (b) **`tools.visible`**: a demoted tool listed there is excluded from `getDeferredToolSummary` and `isDeferredAndHidden` returns false, so it is declared upfront and never counted withheld in any session.

Five copies carry the sentence: this JSDoc, the `allowedTools` JSDoc (~types.ts:468), `packages/vscode-ide-companion/schemas/settings.schema.json:1335`, `packages/cli/src/config/settingsSchema.ts:2802`, and `docs/users/configuration/settings.md:371`.

## 4. Doc accuracy (R4-9): SDK doc rows present tools.eager as THE schema-shrink knob, omitting the exempt set

`docs/developers/sdk-typescript.md:69` and the byte-identical twin `packages/sdk-typescript/README.md:68` say "To keep a tool's schema out of the initial model request, use `tools.eager`" without the exempt-family caveat (`tool_search`, `structured_output`, plan-mode lifecycle tools, `task_stop`, `mcp__*`, `computer_use__*`) that `isExemptFromEagerAllowList` (`permission-manager.ts:800-808`) implements and that the four sibling surfaces shipped by this same PR carry (`settings.md:371`, `types.ts` JSDoc, `settingsSchema.ts:2802`, `settings.schema.json:1335`). `preloadDeferredToolsWithinBudget` excludes only tools demoted BY `tools.eager` (`tool-registry.ts:960-966`), so MCP schemas (exempt from demotion) are preloaded back into the initial declarations under the default threshold. Note: the thread's sub-claim that "the sentence this diff replaced carried the exemption note" does not hold — the pre-`e3e2fcebd1` sentence also lacked it — but the inconsistency at head stands.

## 5. Diagnostic gap (R4-20): typo'd dynamic-family eager entries escape every diagnostic

The `mcp__`/`computer_use__` carve-out in the unknown-entry loop (`permission-manager.ts:280-283`) lets `tools.eager: ["mcp__githb__create_issue"]` parse cleanly, skip the unknown check, and activate a matches-nothing allowlist — silently demoting every non-exempt eager-by-default built-in with zero diagnostic (the built-in typo twin `read_flie` does warn). Nothing validates later: MCP names only exist after `discoverAllTools`, which runs after `initialize()`. Suggested fix: after discovery completes, check `mcp__`/`computer_use__` eager entries against the actually-registered tool set and emit the same warning class for entries that matched nothing (a registry-aware deferral also covers command-discovered names). Pin with a test asserting `console.warn` fires when a `mcp__` eager entry matches nothing and stays silent when it matches.

## 6. Test coverage (R2-17): LS × tools.eager third cell unpinned

`packages/core/src/config/config.test.ts`: the suite pins **disabled+covered → neither** (test at :8941 lists `ListFiles` in the allowlist with `lsToolEnabled` off and asserts LS neither registered nor deferred, :9018-9019) and **enabled+uncovered → deferred** (test at :9022), but not the third reachable cell **enabled+covered → registered eagerly**. The PM-level coverage pin calls `getToolRegistrationStatus` directly, bypassing `Config.createToolRegistry`, so a `registerLazy` mutant that demotes LS whenever an eager list is active (ignoring entry coverage) survives the full suite. Companion case to add: `lsToolEnabled: true, eagerTools: ['Shell', 'ListFiles']` → `expect(registered).toContain(ToolNames.LS)` and `expect(deferred).not.toContain(ToolNames.LS)`.

---

Splitting note: item 3 belongs to the same caveat class as #10339 but is listed here because it additionally omits the two carve-outs; if maintainers prefer, it can be folded into #10339.

**Comment by yiliang114** [comment]
核对了当前 main（03a9fb72e2），结论分两部分：

**1. item 1 的运行时崩溃在 main 上已不存在。** issue 的代码快照基于 PR head `4a51304`，而 #10098 最终合入的 head 是 `de60b7ff`（squash 为 `36de6ebe`），两者之间已经把 R3-9 修掉了：

- `resolveToolName` 现在只认 own property（`Object.hasOwn(TOOL_NAME_ALIASES, rawName)`），prototype key（`constructor`/`toString`/…）会原样返回字符串，不再读出继承的函数值（`rule-parser.ts`，parser 级测试 `resolveToolName('constructor')` 也已存在）；
- 崩溃所在的 unknown-entry 循环（`rule.toolName.startsWith(...)`）在合入版本里已整体移除，`initialize()` 的 eager 解析只丢弃空/非法项，不再对 `toolName` 调用字符串方法。

所以无法在当前 main 上写出红测试——崩溃路径已闭合。

**2. 其余 item 在 main 上逐一核实，仍成立的有：**

- item 2：`settings.md` 两处 "permissions.deny removes a tool outright / entirely" 对 MCP 工具不成立（MCP 注册只查 `tools.disabled`，deny 只在调用时拒绝）——已确认（`tool-registry.ts` `registerTool`/`isToolDisabled`）；
- item 3：ToolSearch-absent caveat 的 5 份副本确实漏了 resumed-session history re-reveal 和 `tools.visible` 两个 carve-out——代码里两个 carve-out 都在（`client.ts` `revealDeferredToolsReferencedInHistory` / `resolveDeferredToolsForReminder`、`getDeferredToolSummary`）；
- item 4：`docs/developers/sdk-typescript.md` 与 `packages/sdk-typescript/README.md` 的 eager 描述确实漏了 exempt 集；
- item 6：`config.test.ts` 确实缺 "LS enabled + eager covered → registered eagerly" 第三格（现有两格：disabled+covered→neither、enabled+uncovered→deferred）。

**3. item 5 留作后续。** 合入版本已删掉 initialize 期的 unknown-entry 警告，要做就得在 `discoverAllTools` 之后做 registry-aware 校验，涉及增量 MCP discovery、别名归一化等场景，不属于小改动，本 PR 不带上。

接下来提一个 PR：补 issue 要求的回归保护测试（`eagerTools: ['constructor']` 等 prototype key 下 `initialize()` 不抛、别名解析不受影响）、补第三格测试、修正上述文档措辞。`Part of #10400`。

**Comment by yiliang114** [comment]
Status check against current `main` (post-#10098 merge): **item 1 (Critical) no longer reproduces** — the crash path is gone:

- `resolveToolName` (rule-parser.ts:312-315) now resolves via `Object.hasOwn(TOOL_NAME_ALIASES, rawName)` and can no longer return an inherited `Object.prototype` value, so `parseRule` always yields a string `toolName`.
- The unknown-entry loop that threw (`rule.toolName.startsWith is not a function`) no longer exists; unusable entries are now flagged `invalid` by `parseRule` and dropped with the `tools.eager: ignoring … unusable entries` warning, matching the PR's contract.

So `tools.eager: ["constructor"]` (and the other prototype-key entries) no longer crash `PermissionManager.initialize()`.

Items 2–6 (doc accuracy ×3, post-discovery typo'd `mcp__`/`computer_use__` eager-entry diagnostic, LS×eager test pin) remain open as documented here.

**Comment by yiliang114** [comment]
Closing this as the original startup crash (item 1) was fixed by #10098 and regression-tested together with items 2–4 and 6 in #10479.

The remaining dynamic `tools.eager` diagnostic gap (item 5) is now tracked separately in #12435.
